name: unit tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" , "develop"]

permissions:
  contents: read

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install
      run: pip install -r requirements.txt
    - name: Unit tests
      run: python -m unittest tests/test_visit_sensor.py
    - name: Check format
      run: |
        black --check --verbose .